name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-pr
        uses: actions/labeler@v5
        run: echo "Labeling the PR"
      
      - id: output-the-label
        run: echo "Branch ${{ github.ref }} was labelled as ${{ steps.label-the-PR.outputs.all-labels }}"
