name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - id: label-the-pr
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler-settings.yml'
      - run: echo "The branch ${{ github.head_ref || github.ref_name }} was labeled as ${{ steps.label-the-PR.outputs.all-labels }}."
