name: 'Unit Tests'
on:
  - pull-request

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Run Tests
        run: |
          npm ci
          npm test